import './lib/accordion';
import './lib/audio-player';
import './lib/autocomplete-search';
import './lib/atoz';
import './lib/degree-finder';
import './lib/equalizer';
import './lib/external-link';
import './lib/form';
import './lib/filter-grid';
// import './lib/mobile-page-title';
import './lib/image-gallery';
import './lib/interchange';
import './lib/picture';
import './lib/responsive-video';
import './lib/services-menu';
import './lib/site-menu';
import './lib/smooth-scroll';
import './lib/tabs';
import './lib/tables-scrollbar';
import './lib/tooltip';
// import './lib/data-tooltip';
import './lib/vegas';
